GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/15

###

POST http://deploynode.app.ruk-com.cloud/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Web Dev Simplified"
}

###


###
PATCH  http://deploynode.app.ruk-com.cloud/subscribers
Content-Type: application/json

{
    "name": "Homer"
}